export const GET_FORUM_CATEGORIES_REQUEST = 'GET_FORUM_CATEGORIES_REQUEST'
export const GET_FORUM_CATEGORIES_SUCCESS = 'GET_FORUM_CATEGORIES_SUCCESS'
export const GET_FORUM_CATEGORIES_FAILURE = 'GET_FORUM_CATEGORIES_FAILURE'

export const SELECT_FORUM_INTEREST_CATEGORY = 'SELECT_FORUM_INTEREST_CATEGORY'
export const SELECT_FORUM_INTEREST_SUBCATEGORY =
  'SELECT_FORUM_INTEREST_SUBCATEGORY'
