export const GET_NOTIFICATIONS_REQUEST = 'get_notifications_request'
export const GET_NOTIFICATIONS_SUCCESS = 'get_notifications_success'
export const GET_NOTIFICATIONS_FAILURE = 'get_notifications_failure'
export const SEEN_NOTIFICATIONS_REQUEST = 'seen_notifications_request'
export const SEEN_NOTIFICATIONS_SUCCESS = 'seen_notifications_success'
export const SEEN_NOTIFICATIONS_FAILURE = 'seen_notifications_failure'
