export const SELECT_FORUM_FORM_CATEGORY = 'select_forum_form_category'
export const CREATE_FORUM_POST_REQUEST = 'create_new_forum_post_request'
export const CREATE_FORUM_POST_SUCCESS = 'create_new_forum_post_success'
export const CREATE_FORUM_POST_FAILURE = 'create_new_forum_post_failure'
export const FORUM_POST_LOADING = 'forum_post_loading'
export const FORUM_POST_NOT_LOADING = 'forum_post_not_loading'
