require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Flornt' do
  config = use_native_modules!

  use_react_native!(path: config['reactNativePath'], hermes_enabled: true)

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.88.0' })

  pod 'RNSound', path: '../node_modules/react-native-sound'

  pod 'RNAudio', path: '../node_modules/react-native-audio'

  pod 'RNVectorIcons', path: '../node_modules/react-native-vector-icons'

  pod 'react-native-safe-area-context', path: '../node_modules/react-native-safe-area-context'

  post_install do |installer|
    flipper_post_install(installer)
  end

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Notifications', path: "#{permissions_path}/Notifications.podspec"
end
